# Tell Hibernate to automatically update database schemas to match Java entities
jakarta.persistence.schema-generation.database.action=update
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Default to SQLite if no profile is explicitly passed
spring.datasource.url=jdbc:sqlite:orm_system.db?foreign_keys=on
server.servlet.context-path=/api/v1