# Import config.yml
spring.config.import=optional:classpath:config.yml
# Map nice properties to the internal ones
spring.jpa.show-sql=${app.debug.show_sql}
spring.datasource.url=${server.database}
logging.level.root=${app.logging.level}
logging.file.name=${app.logging.path}
logging.logback.rollingpolicy.max-file-size=${app.logging.rolling.max-file-size}
logging.logback.rollingpolicy.max-history=${app.logging.rolling.max-history}
logging.logback.rollingpolicy.total-size-cap=${app.logging.rolling.total-size-cap}
logging.logback.rollingpolicy.clean-history-on-start=${app.logging.rolling.clean-history-on-start}
server.servlet.context-path=/api/v1
# Tell Hibernate to automatically update database schemas to match Java entities
jakarta.persistence.schema-generation.database.action=update
spring.jpa.hibernate.ddl-auto=update