#####################
# ORM Configuration #
#####################
# This is the local configuration file for ORM.
# It has the second-highest precedence when loading configuration options.
# The order of precedence is: Environment Variables > Configuration File > Database.

# Config that affects the whole workgroup
workgroup:
  # JDBC URL for the workgroup database
  database: jdbc:sqlite:orm_system.db

# Config that affects just the server that is reading the config
server:
  plugins:
    # Define the directory to load plugins from
    directory: ./plugins
    # Skip the check during startup to ensure all plugins are required plugins are loaded
    skip_startup_check: false
  debug:
    # If enabled, detailed API error messages will be returned to the user
    detailed_errors: true
    # If enabled, will print SQL statements to the log
    show_sql: false
  logging:
    # Define the minimum log level for writing to logs
    level: INFO
    # Define the path that logs should be stored
    path: ./logs/openrecordsmanager.log
    # Define a rolling log policy
    rolling:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 100MB
      clean-history-on-start: false
