plugins {
    id 'java'
}

dependencies {
    compileOnly project(':plugin-api')

    testImplementation project(':plugin-api')
    testImplementation 'org.junit.jupiter:junit-jupiter:5.12.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test', Test) {
    useJUnitPlatform()
}
