<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.openrecordsmanager</groupId>
    <artifactId>orm-server</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <modules>
        <module>plugin-api</module>
        <module>plugins/auth-local</module>
        <module>plugins/auth-oidc</module>
        <module>plugins/defaults-aus-gov</module>
        <module>plugins/filestore-local</module>
        <module>plugins/filestore-s3</module>
        <module>server-core</module>
    </modules>

    <properties>
        <revision>0.1.0</revision>
        <spring-boot-version>4.0.6</spring-boot-version>

        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <profiles>
        <profile>
            <id>run-server</id>
            <properties>
                <spring-boot.run.skip>true</spring-boot.run.skip>
            </properties>
            <build>
                <defaultGoal>package</defaultGoal>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <version>${spring-boot-version}</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>run</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.4.2</version>
                    <configuration>
                        <archive>
                            <manifestEntries>
                                <Plugin-Id>${project.artifactId}</Plugin-Id>
                                <Plugin-Version>${project.version}</Plugin-Version>
                            </manifestEntries>
                        </archive>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

</project>