// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

/**
 * Field-level validation error
 */
export type ApiFieldError = {
    error: string;
    errorArgs?: Array<string>;
};

/**
 * Failed API envelope
 */
export type ApiErrorResponse = {
    success: false;
    timestamp: string;
    error: string;
    errorArgs?: Array<string>;
    fieldErrors?: {
        [key: string]: ApiFieldError;
    };
};

/**
 * Successful API envelope without payload
 */
export type ApiSuccessEnvelope = {
    success: true;
    timestamp: string;
};

export type TranslationOverrideRequest = {
    messageKey: string;
    locale: string;
    value: string;
};

export type TranslationOverrideResponse = {
    messageKey: string;
    locale: string;
    value: string;
    updatedAt: string;
};

export type UpdateRecordRequest = {
    type?: string;
    title?: string;
    properties?: {
        [key: string]: unknown;
    };
};

export type RecordResponse = {
    id: string;
    type: string;
    properties: {
        [key: string]: unknown;
    };
    revisions: Array<string>;
};

export type UpdatePluginRequest = {
    enabled?: boolean;
};

export type PluginResponse = {
    id: string;
    version: string;
    enabled: boolean;
    dateCreated: string;
    dateModified: string;
    loaded: boolean;
};

export type UpdateObjectPropertyRequest = {
    name: string;
    description: string;
    validator?: string;
    securityFilter?: string;
    /**
     * Arbitrary JSON value (string, number, boolean, object, array, or null)
     */
    defaultValue?: unknown;
    userHidden: boolean;
};

export type ObjectPropertyResponse = {
    id: string;
    type: string;
    listType?: string;
    validator?: string;
    securityFilter?: string;
    /**
     * Arbitrary JSON value (string, number, boolean, object, array, or null)
     */
    defaultValue?: unknown;
    userHidden: boolean;
    dateCreated: string;
    dateModified: string;
};

export type UpdateLocationRequest = {
    authProvider?: string;
    enabled?: boolean;
    name?: string;
    properties?: {
        [key: string]: unknown;
    };
};

export type LocationResponse = {
    id: string;
    type: string;
    name: string;
    displayName: string;
    kind: 'user' | 'group' | 'any';
    authProvider?: string;
    enabled?: boolean;
    properties: {
        [key: string]: unknown;
    };
};

export type UpdateLocationRelationshipTypeRequest = {
    sourceKind?: 'user' | 'group' | 'any';
    targetKind?: 'user' | 'group' | 'any';
    uniquePerSource?: boolean;
};

export type LocationRelationshipTypeResponse = {
    id: string;
    sourceKind: 'user' | 'group' | 'any';
    targetKind: 'user' | 'group' | 'any';
    uniquePerSource: boolean;
};

export type UpdateListTypeRequest = {
    name: string;
};

export type ListElementResponse = {
    type: string;
    aliases: Array<string>;
    index: number;
    activeTo?: string;
    dateCreated: string;
    dateModified: string;
};

export type ListTypeResponse = {
    type?: string;
    dateCreated: string;
    dateModified: string;
    elements: Array<ListElementResponse>;
};

export type UpdateListElementRequest = {
    name: string;
    description: string;
    index: number;
    activeTo?: string;
    aliases: Array<string>;
};

export type UpdateFileStoreRequest = {
    name?: string;
    properties?: {
        [key: string]: unknown;
    };
};

export type SimpleFileStoreResponse = {
    id: string;
    name: string;
    type: string;
};

export type UpdateFileStoreMiddlewareRequest = {
    name?: string;
    properties?: {
        [key: string]: unknown;
    };
};

export type SimpleMiddlewareResponse = {
    id: string;
    name: string;
    type: string;
};

export type ConfigResponse = {
    key: string;
    /**
     * Arbitrary JSON value (string, number, boolean, object, array, or null)
     */
    value?: unknown;
    dateModified: string;
};

export type ComponentReference = {
    id: string;
    type: string;
};

export type NewAuthProviderRequest = {
    name: string;
    type: ComponentReference;
    settings: {
        [key: string]: unknown;
    };
};

export type AuthProviderResponse = {
    id: string;
    name: string;
    type: ComponentReference;
    enabled: boolean;
    /**
     * Provider settings with write-only fields omitted
     */
    settings?: {
        [key: string]: unknown;
    };
    dateCreated: string;
    dateModified: string;
};

export type UpdateAuthProviderRequest = {
    name?: string;
    enabled?: boolean;
    settings?: {
        [key: string]: unknown;
    };
};

export type UpdateAuditPolicyRequest = {
    enabled: boolean;
    requiresComment: boolean;
};

export const AuditOperation = {
    CREATE: 'CREATE',
    READ: 'READ',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE',
    ACTION: 'ACTION'
} as const;

export type AuditOperation = typeof AuditOperation[keyof typeof AuditOperation];

export type AuditPolicyResponse = {
    entityType: 'record' | 'record_type' | 'location' | 'location_relationship' | 'location_relationship_type' | 'location_type' | 'config' | 'list' | 'list_element' | 'object_property' | 'file_store' | 'auth_provider' | 'record_revision' | 'file_store_middleware' | 'template' | 'plugin';
    operation: AuditOperation;
    enabled: boolean;
    requiresComment: boolean;
    dateModified: string;
};

export const TemplateType = {
    LIST: 'list',
    LIST_ELEMENT: 'list_element',
    OBJECT_PROPERTY: 'object_property',
    RECORD_TYPE: 'record_type',
    LOCATION_TYPE: 'location_type',
    LOCATION_RELATIONSHIP_TYPE: 'location_relationship_type'
} as const;

export type TemplateType = typeof TemplateType[keyof typeof TemplateType];

export type NewRecordRequest = {
    type: string;
    title: string;
    /**
     * Property id → JSON value
     */
    properties: {
        [key: string]: unknown;
    };
};

export type ObjectSearchRequest = {
    q?: string;
    filters?: Array<SearchClause>;
    match?: 'ALL' | 'ANY';
    type?: string;
    limit?: number;
    cursor?: string;
};

export type SearchClause = {
    field?: string;
    op?: 'EQ' | 'NEQ' | 'GT' | 'GTE' | 'LT' | 'LTE' | 'LIKE' | 'IN' | 'NOT_IN' | 'IS_NULL' | 'IS_NOT_NULL' | 'BETWEEN';
    /**
     * Arbitrary JSON value (string, number, boolean, object, array, or null)
     */
    value?: unknown;
};

export type RecordSearchResponse = {
    items?: Array<RecordResponse>;
    nextCursor?: string;
};

export type NewObjectPropertyRequest = {
    id: string;
    name: string;
    description: string;
    type: PropertyTypeObject;
    listType?: string;
    validator?: string;
    securityFilter?: string;
    /**
     * Arbitrary JSON value (string, number, boolean, object, array, or null)
     */
    defaultValue?: unknown;
    userHidden: boolean;
};

export type PropertyTypeObject = {
    name?: string;
};

export type NewLocationRequest = {
    type: string;
    authProvider?: string;
    name?: string;
    /**
     * Property id → JSON value
     */
    properties: {
        [key: string]: unknown;
    };
};

export type NewLocationRelationshipRequest = {
    targetId: string;
    typeId: string;
    activeTo?: string;
};

export type LocationRelationshipResponse = {
    id: string;
    sourceId: string;
    targetId: string;
    typeId: string;
    dateCreated: string;
    activeTo?: string;
};

export type LocationSearchResponse = {
    items?: Array<LocationResponse>;
    nextCursor?: string;
};

export type NewLocationRelationshipTypeRequest = {
    id: string;
    sourceKind: 'user' | 'group' | 'any';
    targetKind: 'user' | 'group' | 'any';
    uniquePerSource?: boolean;
};

export type NewListTypeRequest = {
    id: string;
    name: string;
};

export type NewListElementRequest = {
    id: string;
    name: string;
    description: string;
    index?: number;
    activeTo?: string;
    aliases: Array<string>;
};

export type NewFileStoreRequest = {
    name: string;
    type: string;
    properties: {
        [key: string]: unknown;
    };
    middlewares: Array<string>;
};

export type NewFileStoreMiddlewareRequest = {
    name: string;
    type: string;
    properties: {
        [key: string]: unknown;
    };
};

export type SetupStatusResponse = {
    state: 'READY' | 'UPGRADE_REQUIRED';
    currentVersion?: string;
    pendingMigrations: Array<string>;
    migrationsApplied: number;
};

export type LoginResponse = {
    accessToken: string;
    accessExpires: string;
    refreshToken: string;
    refreshExpires: string;
    sessionMode: 'NORMAL' | 'DEGRADED_READ_ONLY';
};

export type WebBrandingResponse = {
    logoUrl: string;
    faviconUrl: string;
    primaryColor: string;
    supportUrl: string;
};

export type TranslationCatalogResponse = {
    locale: string;
    messages: {
        [key: string]: string;
    };
};

export type ComponentReferenceTemplateComponent = {
    type?: ComponentTypeTemplateComponent;
};

export type ComponentTypeTemplateComponent = {
    name?: string;
};

export type TemplateComponent = {
    dependencies?: Array<ComponentReferenceTemplateComponent>;
};

export type ActionResponse = {
    id: string;
    inputSchema: InputFormSchema;
    requiresAuditComment?: boolean;
};

export type InputFormSchema = {
    type: string;
    additionalProperties: boolean;
    properties?: {
        [key: string]: InputFormSchemaField;
    };
    required?: Array<string>;
};

export type InputFormSchemaField = {
    type: string;
    title: string;
    description?: string;
    writeOnly?: boolean;
    format?: string;
    minLength?: number;
    maxLength?: number;
    pattern?: string;
    contentEncoding?: string;
    enum?: Array<string>;
};

export type RecordTypePropertyResponse = {
    property: ObjectPropertyResponse;
    /**
     * Arbitrary JSON value (string, number, boolean, object, array, or null)
     */
    default?: unknown;
};

export type RecordTypeResponse = {
    id: string;
    securityFilter?: string;
    securityFilterUsage: 'HIDE_RECORD' | 'HIDE_FILES' | 'SHOW_ALL';
    contentTypes?: Array<string>;
    properties: Array<RecordTypePropertyResponse>;
    dateCreated: string;
    dateModified: string;
};

export type SimplePluginResponse = {
    id: string;
    version: string;
    enabled: boolean;
    dateModified: string;
    loaded: boolean;
};

export type SimpleObjectPropertyResponse = {
    id: string;
    type: string;
};

export type LocationTypePropertyResponse = {
    property: ObjectPropertyResponse;
    /**
     * Arbitrary JSON value (string, number, boolean, object, array, or null)
     */
    default?: unknown;
};

export type LocationTypeResponse = {
    id: string;
    kind: 'user' | 'group' | 'any';
    properties: Array<LocationTypePropertyResponse>;
    dateCreated: string;
    dateModified: string;
};

export type FileStoreResponse = {
    id: string;
    name: string;
    type: string;
    properties: {
        [key: string]: unknown;
    };
    middlewares: Array<string>;
    fileCount: number;
    dateCreated: string;
    dateModified: string;
};

export type FileStoreTypeResponse = {
    id: string;
    settingsSchema: InputFormSchema;
};

export type MiddlewareResponse = {
    id: string;
    name: string;
    type: string;
    properties: {
        [key: string]: unknown;
    };
    dateCreated: string;
    dateModified: string;
};

export type MiddlewareTypeResponse = {
    id: string;
    settingsSchema: InputFormSchema;
};

/**
 * Boolean configuration value
 */
export type ConfigTypeBooleanResponse = {
    key: string;
    type: 'boolean';
    currentValue?: boolean;
    defaultValue?: boolean;
};

/**
 * Decimal configuration value
 */
export type ConfigTypeDecimalResponse = {
    key: string;
    type: 'decimal';
    currentValue?: number;
    defaultValue?: number;
};

/**
 * Integer list configuration value
 */
export type ConfigTypeIntListResponse = {
    key: string;
    type: 'int_list';
    currentValue?: Array<number>;
    defaultValue?: Array<number>;
};

/**
 * Integer number configuration value
 */
export type ConfigTypeNumberResponse = {
    key: string;
    type: 'number';
    currentValue?: number;
    defaultValue?: number;
};

/**
 * Opaque object configuration value
 */
export type ConfigTypeObjectResponse = {
    key: string;
    type: 'object';
    /**
     * Arbitrary JSON value (string, number, boolean, object, array, or null)
     */
    currentValue?: unknown;
    /**
     * Arbitrary JSON value (string, number, boolean, object, array, or null)
     */
    defaultValue?: unknown;
};

export type ConfigTypeResponse = ({
    type: 'string';
} & ConfigTypeStringResponse) | ({
    type: 'boolean';
} & ConfigTypeBooleanResponse) | ({
    type: 'number';
} & ConfigTypeNumberResponse) | ({
    type: 'decimal';
} & ConfigTypeDecimalResponse) | ({
    type: 'uuid';
} & ConfigTypeUuidResponse) | ({
    type: 'string_list';
} & ConfigTypeStringListResponse) | ({
    type: 'int_list';
} & ConfigTypeIntListResponse) | ({
    type: 'object';
} & ConfigTypeObjectResponse);

/**
 * String list configuration value
 */
export type ConfigTypeStringListResponse = {
    key: string;
    type: 'string_list';
    currentValue?: Array<string>;
    defaultValue?: Array<string>;
};

/**
 * String configuration value
 */
export type ConfigTypeStringResponse = {
    key: string;
    type: 'string';
    currentValue?: string;
    defaultValue?: string;
};

/**
 * UUID configuration value
 */
export type ConfigTypeUuidResponse = {
    key: string;
    type: 'uuid';
    currentValue?: string;
    defaultValue?: string;
};

export type AuthProviderTypeResponse = {
    type: ComponentReference;
    settingsSchema?: InputFormSchema;
};

export type SimpleAuthProviderResponse = {
    id: string;
    name: string;
    type: ComponentReference;
    loginSchema?: InputFormSchema;
};

export type AuditStatusResponse = {
    auditEnabled: boolean;
    auditDisabledReason?: string;
    primaryWritable: boolean;
    pendingSpoolCount: number;
    archiveEnabled: boolean;
    drainIntervalSeconds: number;
    lastProbeAt: string;
    lastSuccessfulWriteAt: string;
    lastDrainAttemptAt: string;
    lastSuccessfulDrainAt: string;
};

export type AuditEventResponse = {
    id?: string;
    occurredAt?: string;
    actorId?: string;
    actorUsername?: string;
    operation?: 'CREATE' | 'READ' | 'UPDATE' | 'DELETE' | 'ACTION';
    targetType?: 'record' | 'record_type' | 'location' | 'location_relationship' | 'location_relationship_type' | 'location_type' | 'config' | 'list' | 'list_element' | 'object_property' | 'file_store' | 'auth_provider' | 'record_revision' | 'file_store_middleware' | 'template' | 'plugin';
    targetId?: string;
    actionId?: string;
    summary?: string;
    changes?: Array<AuditPropertyChange>;
    relationships?: Array<AuditRelationship>;
    comment?: string;
    metadata?: {
        [key: string]: unknown;
    };
};

export type AuditPropertyChange = {
    property?: string;
    /**
     * Arbitrary JSON value (string, number, boolean, object, array, or null)
     */
    oldValue?: unknown;
    /**
     * Arbitrary JSON value (string, number, boolean, object, array, or null)
     */
    newValue?: unknown;
};

export type AuditRelationship = {
    type?: 'record' | 'record_type' | 'location' | 'location_relationship' | 'location_relationship_type' | 'location_type' | 'config' | 'list' | 'list_element' | 'object_property' | 'file_store' | 'auth_provider' | 'record_revision' | 'file_store_middleware' | 'template' | 'plugin';
    id?: string;
    role?: string;
};

export type ListTranslationOverridesData = {
    body?: never;
    path?: never;
    query?: {
        prefix?: string;
        locale?: string;
    };
    url: '/api/translations/overrides';
};

export type ListTranslationOverridesErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type ListTranslationOverridesError = ListTranslationOverridesErrors[keyof ListTranslationOverridesErrors];

export type ListTranslationOverridesResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: Array<TranslationOverrideResponse>;
    };
};

export type ListTranslationOverridesResponse = ListTranslationOverridesResponses[keyof ListTranslationOverridesResponses];

export type UpsertTranslationOverrideData = {
    body: TranslationOverrideRequest;
    path?: never;
    query?: never;
    url: '/api/translations/overrides';
};

export type UpsertTranslationOverrideErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type UpsertTranslationOverrideError = UpsertTranslationOverrideErrors[keyof UpsertTranslationOverrideErrors];

export type UpsertTranslationOverrideResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: TranslationOverrideResponse;
    };
};

export type UpsertTranslationOverrideResponse = UpsertTranslationOverrideResponses[keyof UpsertTranslationOverrideResponses];

export type GetData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/records/{id}';
};

export type GetErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type GetError = GetErrors[keyof GetErrors];

export type GetResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: RecordResponse;
    };
};

export type GetResponse = GetResponses[keyof GetResponses];

export type UpdateData = {
    body: UpdateRecordRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/records/{id}';
};

export type UpdateErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type UpdateError = UpdateErrors[keyof UpdateErrors];

export type UpdateResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: RecordResponse;
    };
};

export type UpdateResponse = UpdateResponses[keyof UpdateResponses];

export type GetRevisionData = {
    body?: never;
    path: {
        id: string;
        version: string;
    };
    query?: never;
    url: '/api/records/{id}/{version}';
};

export type GetRevisionErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type GetRevisionError = GetRevisionErrors[keyof GetRevisionErrors];

export type GetRevisionResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type GetRevisionResponse = GetRevisionResponses[keyof GetRevisionResponses];

export type CreateRevision2Data = {
    body?: {
        stream: Blob | File;
    };
    headers?: {
        'Content-Disposition'?: string;
    };
    path: {
        id: string;
        version: string;
    };
    query?: {
        ext?: string;
    };
    url: '/api/records/{id}/{version}';
};

export type CreateRevision2Errors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type CreateRevision2Error = CreateRevision2Errors[keyof CreateRevision2Errors];

export type CreateRevision2Responses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: ApiSuccessEnvelope & {
            data: RecordResponse;
        };
    };
};

export type CreateRevision2Response = CreateRevision2Responses[keyof CreateRevision2Responses];

export type DeletePluginData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/plugins/{id}';
};

export type DeletePluginErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type DeletePluginError = DeletePluginErrors[keyof DeletePluginErrors];

export type DeletePluginResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope;
};

export type DeletePluginResponse = DeletePluginResponses[keyof DeletePluginResponses];

export type GetPluginData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/plugins/{id}';
};

export type GetPluginErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type GetPluginError = GetPluginErrors[keyof GetPluginErrors];

export type GetPluginResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: PluginResponse;
    };
};

export type GetPluginResponse = GetPluginResponses[keyof GetPluginResponses];

export type UpdatePluginData = {
    body: UpdatePluginRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/plugins/{id}';
};

export type UpdatePluginErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type UpdatePluginError = UpdatePluginErrors[keyof UpdatePluginErrors];

export type UpdatePluginResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: PluginResponse;
    };
};

export type UpdatePluginResponse = UpdatePluginResponses[keyof UpdatePluginResponses];

export type ObjectPropertyDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/object_properties/{id}';
};

export type ObjectPropertyDeleteErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Resource in use
     */
    409: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type ObjectPropertyDeleteError = ObjectPropertyDeleteErrors[keyof ObjectPropertyDeleteErrors];

export type ObjectPropertyDeleteResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope;
};

export type ObjectPropertyDeleteResponse = ObjectPropertyDeleteResponses[keyof ObjectPropertyDeleteResponses];

export type ObjectPropertyRetrieveOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/object_properties/{id}';
};

export type ObjectPropertyRetrieveOneErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type ObjectPropertyRetrieveOneError = ObjectPropertyRetrieveOneErrors[keyof ObjectPropertyRetrieveOneErrors];

export type ObjectPropertyRetrieveOneResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: ObjectPropertyResponse;
    };
};

export type ObjectPropertyRetrieveOneResponse = ObjectPropertyRetrieveOneResponses[keyof ObjectPropertyRetrieveOneResponses];

export type ObjectPropertyUpdateData = {
    body: UpdateObjectPropertyRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/object_properties/{id}';
};

export type ObjectPropertyUpdateErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type ObjectPropertyUpdateError = ObjectPropertyUpdateErrors[keyof ObjectPropertyUpdateErrors];

export type ObjectPropertyUpdateResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: ObjectPropertyResponse;
    };
};

export type ObjectPropertyUpdateResponse = ObjectPropertyUpdateResponses[keyof ObjectPropertyUpdateResponses];

export type GetLocationData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/location/{id}';
};

export type GetLocationErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type GetLocationError = GetLocationErrors[keyof GetLocationErrors];

export type GetLocationResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: LocationResponse;
    };
};

export type GetLocationResponse = GetLocationResponses[keyof GetLocationResponses];

export type UpdateLocationData = {
    body: UpdateLocationRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/location/{id}';
};

export type UpdateLocationErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Resource in use
     */
    409: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type UpdateLocationError = UpdateLocationErrors[keyof UpdateLocationErrors];

export type UpdateLocationResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: LocationResponse;
    };
};

export type UpdateLocationResponse = UpdateLocationResponses[keyof UpdateLocationResponses];

export type GetLocationRelationshipTypeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/location-relationship-type/{id}';
};

export type GetLocationRelationshipTypeErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type GetLocationRelationshipTypeError = GetLocationRelationshipTypeErrors[keyof GetLocationRelationshipTypeErrors];

export type GetLocationRelationshipTypeResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: LocationRelationshipTypeResponse;
    };
};

export type GetLocationRelationshipTypeResponse = GetLocationRelationshipTypeResponses[keyof GetLocationRelationshipTypeResponses];

export type UpdateLocationRelationshipTypeData = {
    body: UpdateLocationRelationshipTypeRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/location-relationship-type/{id}';
};

export type UpdateLocationRelationshipTypeErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type UpdateLocationRelationshipTypeError = UpdateLocationRelationshipTypeErrors[keyof UpdateLocationRelationshipTypeErrors];

export type UpdateLocationRelationshipTypeResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: LocationRelationshipTypeResponse;
    };
};

export type UpdateLocationRelationshipTypeResponse = UpdateLocationRelationshipTypeResponses[keyof UpdateLocationRelationshipTypeResponses];

export type DeleteListData = {
    body?: never;
    path: {
        list: string;
    };
    query?: never;
    url: '/api/lists/{list}';
};

export type DeleteListErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Resource in use
     */
    409: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type DeleteListError = DeleteListErrors[keyof DeleteListErrors];

export type DeleteListResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope;
};

export type DeleteListResponse = DeleteListResponses[keyof DeleteListResponses];

export type GetListData = {
    body?: never;
    path: {
        list: string;
    };
    query?: never;
    url: '/api/lists/{list}';
};

export type GetListErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type GetListError = GetListErrors[keyof GetListErrors];

export type GetListResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: ListTypeResponse;
    };
};

export type GetListResponse = GetListResponses[keyof GetListResponses];

export type CreateListElementData = {
    body: NewListElementRequest;
    path: {
        list: string;
    };
    query?: never;
    url: '/api/lists/{list}';
};

export type CreateListElementErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Resource in use
     */
    409: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type CreateListElementError = CreateListElementErrors[keyof CreateListElementErrors];

export type CreateListElementResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: ListElementResponse;
    };
};

export type CreateListElementResponse = CreateListElementResponses[keyof CreateListElementResponses];

export type UpdateListData = {
    body: UpdateListTypeRequest;
    path: {
        list: string;
    };
    query?: never;
    url: '/api/lists/{list}';
};

export type UpdateListErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type UpdateListError = UpdateListErrors[keyof UpdateListErrors];

export type UpdateListResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: ListTypeResponse;
    };
};

export type UpdateListResponse = UpdateListResponses[keyof UpdateListResponses];

export type DeleteListElementData = {
    body?: never;
    path: {
        list: string;
        element: string;
    };
    query?: never;
    url: '/api/lists/{list}/{element}';
};

export type DeleteListElementErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type DeleteListElementError = DeleteListElementErrors[keyof DeleteListElementErrors];

export type DeleteListElementResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope;
};

export type DeleteListElementResponse = DeleteListElementResponses[keyof DeleteListElementResponses];

export type GetListElementData = {
    body?: never;
    path: {
        list: string;
        element: string;
    };
    query?: never;
    url: '/api/lists/{list}/{element}';
};

export type GetListElementErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type GetListElementError = GetListElementErrors[keyof GetListElementErrors];

export type GetListElementResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: ListElementResponse;
    };
};

export type GetListElementResponse = GetListElementResponses[keyof GetListElementResponses];

export type UpdateListElementData = {
    body: UpdateListElementRequest;
    path: {
        list: string;
        element: string;
    };
    query?: never;
    url: '/api/lists/{list}/{element}';
};

export type UpdateListElementErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type UpdateListElementError = UpdateListElementErrors[keyof UpdateListElementErrors];

export type UpdateListElementResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: ListElementResponse;
    };
};

export type UpdateListElementResponse = UpdateListElementResponses[keyof UpdateListElementResponses];

export type FileStoreDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/file_stores/{id}';
};

export type FileStoreDeleteErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Resource in use
     */
    409: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type FileStoreDeleteError = FileStoreDeleteErrors[keyof FileStoreDeleteErrors];

export type FileStoreDeleteResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope;
};

export type FileStoreDeleteResponse = FileStoreDeleteResponses[keyof FileStoreDeleteResponses];

export type FileStoreRetrieveOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/file_stores/{id}';
};

export type FileStoreRetrieveOneErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type FileStoreRetrieveOneError = FileStoreRetrieveOneErrors[keyof FileStoreRetrieveOneErrors];

export type FileStoreRetrieveOneResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: FileStoreResponse;
    };
};

export type FileStoreRetrieveOneResponse = FileStoreRetrieveOneResponses[keyof FileStoreRetrieveOneResponses];

export type FileStoreUpdateData = {
    body: UpdateFileStoreRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/file_stores/{id}';
};

export type FileStoreUpdateErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type FileStoreUpdateError = FileStoreUpdateErrors[keyof FileStoreUpdateErrors];

export type FileStoreUpdateResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: SimpleFileStoreResponse;
    };
};

export type FileStoreUpdateResponse = FileStoreUpdateResponses[keyof FileStoreUpdateResponses];

export type MiddlewareDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/file_stores/middlewares/{id}';
};

export type MiddlewareDeleteErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Resource in use
     */
    409: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type MiddlewareDeleteError = MiddlewareDeleteErrors[keyof MiddlewareDeleteErrors];

export type MiddlewareDeleteResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope;
};

export type MiddlewareDeleteResponse = MiddlewareDeleteResponses[keyof MiddlewareDeleteResponses];

export type MiddlewareRetrieveOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/file_stores/middlewares/{id}';
};

export type MiddlewareRetrieveOneErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type MiddlewareRetrieveOneError = MiddlewareRetrieveOneErrors[keyof MiddlewareRetrieveOneErrors];

export type MiddlewareRetrieveOneResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: MiddlewareResponse;
    };
};

export type MiddlewareRetrieveOneResponse = MiddlewareRetrieveOneResponses[keyof MiddlewareRetrieveOneResponses];

export type MiddlewareUpdateData = {
    body: UpdateFileStoreMiddlewareRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/file_stores/middlewares/{id}';
};

export type MiddlewareUpdateErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type MiddlewareUpdateError = MiddlewareUpdateErrors[keyof MiddlewareUpdateErrors];

export type MiddlewareUpdateResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: SimpleMiddlewareResponse;
    };
};

export type MiddlewareUpdateResponse = MiddlewareUpdateResponses[keyof MiddlewareUpdateResponses];

export type SetConfigsData = {
    /**
     * Config key → JSON value
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/config/';
};

export type SetConfigsErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type SetConfigsError = SetConfigsErrors[keyof SetConfigsErrors];

export type SetConfigsResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: Array<ConfigResponse>;
    };
};

export type SetConfigsResponse = SetConfigsResponses[keyof SetConfigsResponses];

export type RetrieveAllAuthProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/providers';
};

export type RetrieveAllAuthProvidersErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type RetrieveAllAuthProvidersError = RetrieveAllAuthProvidersErrors[keyof RetrieveAllAuthProvidersErrors];

export type RetrieveAllAuthProvidersResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: Array<AuthProviderResponse>;
    };
};

export type RetrieveAllAuthProvidersResponse = RetrieveAllAuthProvidersResponses[keyof RetrieveAllAuthProvidersResponses];

export type CreateAuthProviderData = {
    body: NewAuthProviderRequest;
    path?: never;
    query?: never;
    url: '/api/auth/providers';
};

export type CreateAuthProviderErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type CreateAuthProviderError = CreateAuthProviderErrors[keyof CreateAuthProviderErrors];

export type CreateAuthProviderResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: AuthProviderResponse;
    };
};

export type CreateAuthProviderResponse = CreateAuthProviderResponses[keyof CreateAuthProviderResponses];

export type GetAuthProviderData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/auth/providers/{id}';
};

export type GetAuthProviderErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type GetAuthProviderError = GetAuthProviderErrors[keyof GetAuthProviderErrors];

export type GetAuthProviderResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: AuthProviderResponse;
    };
};

export type GetAuthProviderResponse = GetAuthProviderResponses[keyof GetAuthProviderResponses];

export type UpdateAuthProviderData = {
    body: UpdateAuthProviderRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/auth/providers/{id}';
};

export type UpdateAuthProviderErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type UpdateAuthProviderError = UpdateAuthProviderErrors[keyof UpdateAuthProviderErrors];

export type UpdateAuthProviderResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: AuthProviderResponse;
    };
};

export type UpdateAuthProviderResponse = UpdateAuthProviderResponses[keyof UpdateAuthProviderResponses];

export type ListAuditPoliciesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/audit/policies';
};

export type ListAuditPoliciesErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type ListAuditPoliciesError = ListAuditPoliciesErrors[keyof ListAuditPoliciesErrors];

export type ListAuditPoliciesResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: Array<AuditPolicyResponse>;
    };
};

export type ListAuditPoliciesResponse = ListAuditPoliciesResponses[keyof ListAuditPoliciesResponses];

export type UpdateAuditPolicyData = {
    body: UpdateAuditPolicyRequest;
    path?: never;
    query: {
        entityType: string;
        operation: 'CREATE' | 'READ' | 'UPDATE' | 'DELETE' | 'ACTION';
    };
    url: '/api/audit/policies';
};

export type UpdateAuditPolicyErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type UpdateAuditPolicyError = UpdateAuditPolicyErrors[keyof UpdateAuditPolicyErrors];

export type UpdateAuditPolicyResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: AuditPolicyResponse;
    };
};

export type UpdateAuditPolicyResponse = UpdateAuditPolicyResponses[keyof UpdateAuditPolicyResponses];

export type RegisterTemplateData = {
    body?: never;
    path: {
        type: TemplateType;
        template: string;
    };
    query?: {
        includeDependencies?: boolean;
    };
    url: '/api/templates/{type}/{template}/register';
};

export type RegisterTemplateErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type RegisterTemplateError = RegisterTemplateErrors[keyof RegisterTemplateErrors];

export type RegisterTemplateResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope;
};

export type RegisterTemplateResponse = RegisterTemplateResponses[keyof RegisterTemplateResponses];

export type NewRecordData = {
    body: NewRecordRequest;
    path?: never;
    query?: never;
    url: '/api/records';
};

export type NewRecordErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type NewRecordError = NewRecordErrors[keyof NewRecordErrors];

export type NewRecordResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: RecordResponse;
    };
};

export type NewRecordResponse = NewRecordResponses[keyof NewRecordResponses];

export type ExecuteActionData = {
    body: {
        [key: string]: unknown;
    };
    path: {
        id: string;
        action: string;
    };
    query?: never;
    url: '/api/records/{id}/actions/{action}';
};

export type ExecuteActionErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type ExecuteActionError = ExecuteActionErrors[keyof ExecuteActionErrors];

export type ExecuteActionResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope;
};

export type ExecuteActionResponse = ExecuteActionResponses[keyof ExecuteActionResponses];

export type SearchData = {
    body: ObjectSearchRequest;
    path?: never;
    query?: never;
    url: '/api/records/search';
};

export type SearchErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type SearchError = SearchErrors[keyof SearchErrors];

export type SearchResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: RecordSearchResponse;
    };
};

export type SearchResponse = SearchResponses[keyof SearchResponses];

export type ListPluginsData = {
    body?: never;
    path?: never;
    query?: {
        includeDisabled?: boolean;
    };
    url: '/api/plugins';
};

export type ListPluginsErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type ListPluginsError = ListPluginsErrors[keyof ListPluginsErrors];

export type ListPluginsResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: Array<SimplePluginResponse>;
    };
};

export type ListPluginsResponse = ListPluginsResponses[keyof ListPluginsResponses];

export type UploadPluginData = {
    body?: {
        file: Blob | File;
    };
    path?: never;
    query: {
        type: 'zip' | 'jar';
    };
    url: '/api/plugins';
};

export type UploadPluginErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Resource in use
     */
    409: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type UploadPluginError = UploadPluginErrors[keyof UploadPluginErrors];

export type UploadPluginResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: PluginResponse;
    };
};

export type UploadPluginResponse = UploadPluginResponses[keyof UploadPluginResponses];

export type ObjectPropertyRetrieveAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/object_properties';
};

export type ObjectPropertyRetrieveAllErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type ObjectPropertyRetrieveAllError = ObjectPropertyRetrieveAllErrors[keyof ObjectPropertyRetrieveAllErrors];

export type ObjectPropertyRetrieveAllResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: Array<SimpleObjectPropertyResponse>;
    };
};

export type ObjectPropertyRetrieveAllResponse = ObjectPropertyRetrieveAllResponses[keyof ObjectPropertyRetrieveAllResponses];

export type ObjectPropertyCreateData = {
    body: NewObjectPropertyRequest;
    path?: never;
    query?: never;
    url: '/api/object_properties';
};

export type ObjectPropertyCreateErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Resource in use
     */
    409: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type ObjectPropertyCreateError = ObjectPropertyCreateErrors[keyof ObjectPropertyCreateErrors];

export type ObjectPropertyCreateResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: ObjectPropertyResponse;
    };
};

export type ObjectPropertyCreateResponse = ObjectPropertyCreateResponses[keyof ObjectPropertyCreateResponses];

export type CreateLocationData = {
    body: NewLocationRequest;
    path?: never;
    query?: never;
    url: '/api/location';
};

export type CreateLocationErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Resource in use
     */
    409: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type CreateLocationError = CreateLocationErrors[keyof CreateLocationErrors];

export type CreateLocationResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: LocationResponse;
    };
};

export type CreateLocationResponse = CreateLocationResponses[keyof CreateLocationResponses];

export type ListLocationRelationshipsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        direction?: 'outgoing' | 'incoming';
        type?: string;
    };
    url: '/api/location/{id}/relationships';
};

export type ListLocationRelationshipsErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type ListLocationRelationshipsError = ListLocationRelationshipsErrors[keyof ListLocationRelationshipsErrors];

export type ListLocationRelationshipsResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: Array<LocationRelationshipResponse>;
    };
};

export type ListLocationRelationshipsResponse = ListLocationRelationshipsResponses[keyof ListLocationRelationshipsResponses];

export type CreateLocationRelationshipData = {
    body: NewLocationRelationshipRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/location/{id}/relationships';
};

export type CreateLocationRelationshipErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Resource in use
     */
    409: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type CreateLocationRelationshipError = CreateLocationRelationshipErrors[keyof CreateLocationRelationshipErrors];

export type CreateLocationRelationshipResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: LocationRelationshipResponse;
    };
};

export type CreateLocationRelationshipResponse = CreateLocationRelationshipResponses[keyof CreateLocationRelationshipResponses];

export type ExecuteLocationActionData = {
    body: {
        [key: string]: unknown;
    };
    path: {
        id: string;
        action: string;
    };
    query?: never;
    url: '/api/location/{id}/actions/{action}';
};

export type ExecuteLocationActionErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type ExecuteLocationActionError = ExecuteLocationActionErrors[keyof ExecuteLocationActionErrors];

export type ExecuteLocationActionResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope;
};

export type ExecuteLocationActionResponse = ExecuteLocationActionResponses[keyof ExecuteLocationActionResponses];

export type SearchLocationsData = {
    body: ObjectSearchRequest;
    path?: never;
    query?: {
        /**
         * Optional location kind filter
         */
        kind?: 'user' | 'group' | 'any';
    };
    url: '/api/location/search';
};

export type SearchLocationsErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type SearchLocationsError = SearchLocationsErrors[keyof SearchLocationsErrors];

export type SearchLocationsResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: LocationSearchResponse;
    };
};

export type SearchLocationsResponse = SearchLocationsResponses[keyof SearchLocationsResponses];

export type ListLocationRelationshipTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/location-relationship-type';
};

export type ListLocationRelationshipTypesErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type ListLocationRelationshipTypesError = ListLocationRelationshipTypesErrors[keyof ListLocationRelationshipTypesErrors];

export type ListLocationRelationshipTypesResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: Array<LocationRelationshipTypeResponse>;
    };
};

export type ListLocationRelationshipTypesResponse = ListLocationRelationshipTypesResponses[keyof ListLocationRelationshipTypesResponses];

export type CreateLocationRelationshipTypeData = {
    body: NewLocationRelationshipTypeRequest;
    path?: never;
    query?: never;
    url: '/api/location-relationship-type';
};

export type CreateLocationRelationshipTypeErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Resource in use
     */
    409: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type CreateLocationRelationshipTypeError = CreateLocationRelationshipTypeErrors[keyof CreateLocationRelationshipTypeErrors];

export type CreateLocationRelationshipTypeResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: LocationRelationshipTypeResponse;
    };
};

export type CreateLocationRelationshipTypeResponse = CreateLocationRelationshipTypeResponses[keyof CreateLocationRelationshipTypeResponses];

export type GetListsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/lists';
};

export type GetListsErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type GetListsError = GetListsErrors[keyof GetListsErrors];

export type GetListsResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: Array<string>;
    };
};

export type GetListsResponse = GetListsResponses[keyof GetListsResponses];

export type CreateListData = {
    body: NewListTypeRequest;
    path?: never;
    query?: never;
    url: '/api/lists';
};

export type CreateListErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Resource in use
     */
    409: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type CreateListError = CreateListErrors[keyof CreateListErrors];

export type CreateListResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: ListTypeResponse;
    };
};

export type CreateListResponse = CreateListResponses[keyof CreateListResponses];

export type FileStoreRetrieveAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/file_stores';
};

export type FileStoreRetrieveAllErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type FileStoreRetrieveAllError = FileStoreRetrieveAllErrors[keyof FileStoreRetrieveAllErrors];

export type FileStoreRetrieveAllResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: Array<SimpleFileStoreResponse>;
    };
};

export type FileStoreRetrieveAllResponse = FileStoreRetrieveAllResponses[keyof FileStoreRetrieveAllResponses];

export type FileStoreCreateData = {
    body: NewFileStoreRequest;
    path?: never;
    query?: never;
    url: '/api/file_stores';
};

export type FileStoreCreateErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type FileStoreCreateError = FileStoreCreateErrors[keyof FileStoreCreateErrors];

export type FileStoreCreateResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: SimpleFileStoreResponse;
    };
};

export type FileStoreCreateResponse = FileStoreCreateResponses[keyof FileStoreCreateResponses];

export type MiddlewareRetrieveAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/file_stores/middlewares';
};

export type MiddlewareRetrieveAllErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type MiddlewareRetrieveAllError = MiddlewareRetrieveAllErrors[keyof MiddlewareRetrieveAllErrors];

export type MiddlewareRetrieveAllResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: Array<SimpleMiddlewareResponse>;
    };
};

export type MiddlewareRetrieveAllResponse = MiddlewareRetrieveAllResponses[keyof MiddlewareRetrieveAllResponses];

export type MiddlewareCreateData = {
    body: NewFileStoreMiddlewareRequest;
    path?: never;
    query?: never;
    url: '/api/file_stores/middlewares';
};

export type MiddlewareCreateErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type MiddlewareCreateError = MiddlewareCreateErrors[keyof MiddlewareCreateErrors];

export type MiddlewareCreateResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: SimpleMiddlewareResponse;
    };
};

export type MiddlewareCreateResponse = MiddlewareCreateResponses[keyof MiddlewareCreateResponses];

export type ValidateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/database/validate';
};

export type ValidateErrors = {
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type ValidateError = ValidateErrors[keyof ValidateErrors];

export type ValidateResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: boolean;
    };
};

export type ValidateResponse = ValidateResponses[keyof ValidateResponses];

export type UpgradeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/database/upgrade';
};

export type UpgradeErrors = {
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type UpgradeError = UpgradeErrors[keyof UpgradeErrors];

export type UpgradeResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: SetupStatusResponse;
    };
};

export type UpgradeResponse = UpgradeResponses[keyof UpgradeResponses];

export type SignupData = {
    body: {
        [key: string]: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/signup';
};

export type SignupErrors = {
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type SignupError = SignupErrors[keyof SignupErrors];

export type SignupResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: string;
    };
};

export type SignupResponse = SignupResponses[keyof SignupResponses];

export type RefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type RefreshErrors = {
    /**
     * Refresh Failed
     */
    401: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type RefreshError = RefreshErrors[keyof RefreshErrors];

export type RefreshResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: LoginResponse;
    };
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutErrors = {
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type LoginData = {
    body: {
        [key: string]: string;
    };
    path: {
        provider: string;
    };
    query?: never;
    url: '/api/auth/login/{provider}';
};

export type LoginErrors = {
    /**
     * Validation failed
     */
    400: ApiErrorResponse;
    /**
     * Authentication Failed
     */
    401: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: LoginResponse;
    };
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type BrandingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/web';
};

export type BrandingErrors = {
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type BrandingError = BrandingErrors[keyof BrandingErrors];

export type BrandingResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: WebBrandingResponse;
    };
};

export type BrandingResponse = BrandingResponses[keyof BrandingResponses];

export type DeleteTranslationOverrideData = {
    body?: never;
    path: {
        messageKey: string;
        locale: string;
    };
    query?: never;
    url: '/api/translations/overrides/{messageKey}/{locale}';
};

export type DeleteTranslationOverrideErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type DeleteTranslationOverrideError = DeleteTranslationOverrideErrors[keyof DeleteTranslationOverrideErrors];

export type DeleteTranslationOverrideResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope;
};

export type DeleteTranslationOverrideResponse = DeleteTranslationOverrideResponses[keyof DeleteTranslationOverrideResponses];

export type GetTranslationOverrideData = {
    body?: never;
    path: {
        messageKey: string;
        locale: string;
    };
    query?: never;
    url: '/api/translations/overrides/{messageKey}/{locale}';
};

export type GetTranslationOverrideErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type GetTranslationOverrideError = GetTranslationOverrideErrors[keyof GetTranslationOverrideErrors];

export type GetTranslationOverrideResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: TranslationOverrideResponse;
    };
};

export type GetTranslationOverrideResponse = GetTranslationOverrideResponses[keyof GetTranslationOverrideResponses];

export type GetTranslationCatalogData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/translations/catalog';
};

export type GetTranslationCatalogErrors = {
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type GetTranslationCatalogError = GetTranslationCatalogErrors[keyof GetTranslationCatalogErrors];

export type GetTranslationCatalogResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: TranslationCatalogResponse;
    };
};

export type GetTranslationCatalogResponse = GetTranslationCatalogResponses[keyof GetTranslationCatalogResponses];

export type ListTemplatesData = {
    body?: never;
    path?: never;
    query?: {
        type?: TemplateType;
    };
    url: '/api/templates';
};

export type ListTemplatesErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type ListTemplatesError = ListTemplatesErrors[keyof ListTemplatesErrors];

export type ListTemplatesResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: Array<ComponentReference>;
    };
};

export type ListTemplatesResponse = ListTemplatesResponses[keyof ListTemplatesResponses];

export type GetTemplateData = {
    body?: never;
    path: {
        type: TemplateType;
        template: string;
    };
    query?: never;
    url: '/api/templates/{type}/{template}';
};

export type GetTemplateErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type GetTemplateError = GetTemplateErrors[keyof GetTemplateErrors];

export type GetTemplateResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: TemplateComponent;
    };
};

export type GetTemplateResponse = GetTemplateResponses[keyof GetTemplateResponses];

export type ListActionsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/records/{id}/actions';
};

export type ListActionsErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type ListActionsError = ListActionsErrors[keyof ListActionsErrors];

export type ListActionsResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: Array<ActionResponse>;
    };
};

export type ListActionsResponse = ListActionsResponses[keyof ListActionsResponses];

export type GetRecordTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/record_types';
};

export type GetRecordTypesErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type GetRecordTypesError = GetRecordTypesErrors[keyof GetRecordTypesErrors];

export type GetRecordTypesResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: Array<RecordTypeResponse>;
    };
};

export type GetRecordTypesResponse = GetRecordTypesResponses[keyof GetRecordTypesResponses];

export type GetRecordTypeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/record_types/{id}';
};

export type GetRecordTypeErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type GetRecordTypeError = GetRecordTypeErrors[keyof GetRecordTypeErrors];

export type GetRecordTypeResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: RecordTypeResponse;
    };
};

export type GetRecordTypeResponse = GetRecordTypeResponses[keyof GetRecordTypeResponses];

export type ListLocationTypesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Optional location kind filter
         */
        kind?: 'user' | 'group' | 'any';
    };
    url: '/api/location_types';
};

export type ListLocationTypesErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type ListLocationTypesError = ListLocationTypesErrors[keyof ListLocationTypesErrors];

export type ListLocationTypesResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: Array<LocationTypeResponse>;
    };
};

export type ListLocationTypesResponse = ListLocationTypesResponses[keyof ListLocationTypesResponses];

export type GetLocationTypeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/location_types/{id}';
};

export type GetLocationTypeErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type GetLocationTypeError = GetLocationTypeErrors[keyof GetLocationTypeErrors];

export type GetLocationTypeResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: LocationTypeResponse;
    };
};

export type GetLocationTypeResponse = GetLocationTypeResponses[keyof GetLocationTypeResponses];

export type ListLocationActionsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/location/{id}/actions';
};

export type ListLocationActionsErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type ListLocationActionsError = ListLocationActionsErrors[keyof ListLocationActionsErrors];

export type ListLocationActionsResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: Array<ActionResponse>;
    };
};

export type ListLocationActionsResponse = ListLocationActionsResponses[keyof ListLocationActionsResponses];

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/location/me';
};

export type MeErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type MeError = MeErrors[keyof MeErrors];

export type MeResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: LocationResponse;
    };
};

export type MeResponse = MeResponses[keyof MeResponses];

export type SearchListElementData = {
    body?: never;
    path: {
        list: string;
    };
    query: {
        value: string;
    };
    url: '/api/lists/{list}/search';
};

export type SearchListElementErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type SearchListElementError = SearchListElementErrors[keyof SearchListElementErrors];

export type SearchListElementResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: Array<ListElementResponse>;
    };
};

export type SearchListElementResponse = SearchListElementResponses[keyof SearchListElementResponses];

export type FileStoreTypeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/file_stores/types';
};

export type FileStoreTypeGetErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type FileStoreTypeGetError = FileStoreTypeGetErrors[keyof FileStoreTypeGetErrors];

export type FileStoreTypeGetResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: Array<FileStoreTypeResponse>;
    };
};

export type FileStoreTypeGetResponse = FileStoreTypeGetResponses[keyof FileStoreTypeGetResponses];

export type FileStoreMiddlewareTypeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/file_stores/middlewares/types';
};

export type FileStoreMiddlewareTypeGetErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type FileStoreMiddlewareTypeGetError = FileStoreMiddlewareTypeGetErrors[keyof FileStoreMiddlewareTypeGetErrors];

export type FileStoreMiddlewareTypeGetResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: Array<MiddlewareTypeResponse>;
    };
};

export type FileStoreMiddlewareTypeGetResponse = FileStoreMiddlewareTypeGetResponses[keyof FileStoreMiddlewareTypeGetResponses];

export type StatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/database/status';
};

export type StatusErrors = {
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type StatusError = StatusErrors[keyof StatusErrors];

export type StatusResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: SetupStatusResponse;
    };
};

export type StatusResponse = StatusResponses[keyof StatusResponses];

export type GetAllConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/config';
};

export type GetAllConfigErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type GetAllConfigError = GetAllConfigErrors[keyof GetAllConfigErrors];

export type GetAllConfigResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: Array<ConfigTypeResponse>;
    };
};

export type GetAllConfigResponse = GetAllConfigResponses[keyof GetAllConfigResponses];

export type GetConfigData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/config/{id}';
};

export type GetConfigErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type GetConfigError = GetConfigErrors[keyof GetConfigErrors];

export type GetConfigResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: {
            [key: string]: unknown;
        };
    };
};

export type GetConfigResponse = GetConfigResponses[keyof GetConfigResponses];

export type GetAllLocalConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/config/this_server';
};

export type GetAllLocalConfigErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type GetAllLocalConfigError = GetAllLocalConfigErrors[keyof GetAllLocalConfigErrors];

export type GetAllLocalConfigResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: {
            [key: string]: {
                [key: string]: unknown;
            };
        };
    };
};

export type GetAllLocalConfigResponse = GetAllLocalConfigResponses[keyof GetAllLocalConfigResponses];

export type GetLocalConfigData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/config/this_server/{id}';
};

export type GetLocalConfigErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type GetLocalConfigError = GetLocalConfigErrors[keyof GetLocalConfigErrors];

export type GetLocalConfigResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: {
            [key: string]: unknown;
        };
    };
};

export type GetLocalConfigResponse = GetLocalConfigResponses[keyof GetLocalConfigResponses];

export type RedirectData = {
    body?: never;
    path: {
        auth_provider: string;
    };
    query?: {
        redirect?: string;
    };
    url: '/api/auth/redirect/{auth_provider}';
};

export type RedirectErrors = {
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type RedirectError = RedirectErrors[keyof RedirectErrors];

export type RedirectResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RetrieveAuthProviderTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/providers/types';
};

export type RetrieveAuthProviderTypesErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type RetrieveAuthProviderTypesError = RetrieveAuthProviderTypesErrors[keyof RetrieveAuthProviderTypesErrors];

export type RetrieveAuthProviderTypesResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: Array<AuthProviderTypeResponse>;
    };
};

export type RetrieveAuthProviderTypesResponse = RetrieveAuthProviderTypesResponses[keyof RetrieveAuthProviderTypesResponses];

export type CallbackData = {
    body?: never;
    path: {
        auth_provider: string;
    };
    query?: never;
    url: '/api/auth/callback/{auth_provider}';
};

export type CallbackErrors = {
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type CallbackError = CallbackErrors[keyof CallbackErrors];

export type CallbackResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RetrieveAvailableAuthProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/available_providers';
};

export type RetrieveAvailableAuthProvidersErrors = {
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type RetrieveAvailableAuthProvidersError = RetrieveAvailableAuthProvidersErrors[keyof RetrieveAvailableAuthProvidersErrors];

export type RetrieveAvailableAuthProvidersResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: Array<SimpleAuthProviderResponse>;
    };
};

export type RetrieveAvailableAuthProvidersResponse = RetrieveAvailableAuthProvidersResponses[keyof RetrieveAvailableAuthProvidersResponses];

export type GetAuditStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/audit/status';
};

export type GetAuditStatusErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type GetAuditStatusError = GetAuditStatusErrors[keyof GetAuditStatusErrors];

export type GetAuditStatusResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: AuditStatusResponse;
    };
};

export type GetAuditStatusResponse = GetAuditStatusResponses[keyof GetAuditStatusResponses];

export type ListAuditEventsData = {
    body?: never;
    path?: never;
    query: {
        targetType: string;
        targetId: string;
        before?: string;
        limit?: number;
    };
    url: '/api/audit/events';
};

export type ListAuditEventsErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type ListAuditEventsError = ListAuditEventsErrors[keyof ListAuditEventsErrors];

export type ListAuditEventsResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: Array<AuditEventResponse>;
    };
};

export type ListAuditEventsResponse = ListAuditEventsResponses[keyof ListAuditEventsResponses];

export type GetAuditEventData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/audit/events/{id}';
};

export type GetAuditEventErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type GetAuditEventError = GetAuditEventErrors[keyof GetAuditEventErrors];

export type GetAuditEventResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope & {
        data: AuditEventResponse;
    };
};

export type GetAuditEventResponse = GetAuditEventResponses[keyof GetAuditEventResponses];

export type EndLocationRelationshipData = {
    body?: never;
    path: {
        id: string;
        relationshipId: string;
    };
    query?: never;
    url: '/api/location/{id}/relationships/{relationshipId}';
};

export type EndLocationRelationshipErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Audit comment required
     */
    422: ApiErrorResponse;
    /**
     * Internal Server error
     */
    500: ApiErrorResponse;
};

export type EndLocationRelationshipError = EndLocationRelationshipErrors[keyof EndLocationRelationshipErrors];

export type EndLocationRelationshipResponses = {
    /**
     * OK
     */
    200: ApiSuccessEnvelope;
};

export type EndLocationRelationshipResponse = EndLocationRelationshipResponses[keyof EndLocationRelationshipResponses];
