#####################
# ORM Configuration #
#####################

server:
  database:
    primary:
      url: jdbc:sqlite:./data/orm_system.db?busy_timeout=5000
  plugins:
    directory: ./plugins
    skip-startup-check: false
  audit-directory: ./data/audit
  web-directory: ./static
  