/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/records/{id}/revisions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get record revision file */
        get: operations["getRevision"];
        /** Upload new record revision */
        put: operations["newRevision"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/file_stores/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get file store details */
        get: operations["fileStore_retrieveOne"];
        /** Modify file store config */
        put: operations["fileStore_update"];
        post?: never;
        /** Delete a file store */
        delete: operations["fileStore_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/file_stores/middlewares/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get file store middleware details */
        get: operations["middleware_retrieveOne"];
        /** Modify file store middleware config */
        put: operations["middleware_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the value of the config from the database */
        get: operations["database_retrieveOne"];
        /** Set a config value in the database */
        put: operations["set"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{type}/{template}/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a template to the database */
        post: operations["registerTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new record */
        post: operations["newRecord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/file_stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all file stores */
        get: operations["fileStore_retrieveAll"];
        put?: never;
        /** Create a new file store */
        post: operations["fileStore_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/file_stores/middlewares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all file store middlewares */
        get: operations["middleware_retrieveAll"];
        put?: never;
        /** Create a new file store middleware */
        post: operations["middleware_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger a login from an authentication provider, implementations vary depending on the provider. */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List templates types available */
        get: operations["getTemplatesForType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List templates available for type */
        get: operations["getTemplatesForType_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{type}/{template}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get template details */
        get: operations["getTemplatesForType_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get record details */
        get: operations["getRecord"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records/{id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all revisions for a record */
        get: operations["getRevisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/record_types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all record types */
        get: operations["getRecordTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/record_types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get record type details */
        get: operations["getRecordType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all list type identifiers */
        get: operations["getLists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lists/{list}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list details */
        get: operations["getList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lists/{list}/{element}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list element details */
        get: operations["getListElement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lists/{list}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search for list elements in a list */
        get: operations["searchListElement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get basic details about the environment */
        get: operations["getEnvironment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get config values from the database */
        get: operations["database_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/this_server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the effective config values for this specific server */
        get: operations["server_retrieveAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/this_server/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the effective value for the config this specific server */
        get: operations["server_retrieveOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/redirect/{auth_provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trigger a redirect from an authentication provider, implementations vary depending on the provider. */
        get: operations["redirect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback/{auth_provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trigger a callback authentication provider, implementations vary depending on the provider. */
        get: operations["callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponseWrapper: {
            success?: boolean;
            error?: string;
            /** Format: date-time */
            timestamp?: string;
            data?: unknown;
        };
        FileStoreEntry: {
            /** Format: uuid */
            id?: string;
            store?: components["schemas"]["FileStoreObject"];
            path?: string;
            hashAlgorithm?: string;
            hash?: string;
            /** Format: int64 */
            sizeBytes?: number;
            extension?: string | null;
        };
        FileStoreMiddlewareObject: {
            /** Format: uuid */
            id?: string;
            type?: string;
            properties?: {
                [key: string]: unknown;
            };
        };
        FileStoreMiddlewareUsage: {
            middleware?: components["schemas"]["FileStoreMiddlewareObject"];
            /** Format: int32 */
            applicationOrder?: number;
        };
        FileStoreObject: {
            /** Format: uuid */
            id?: string;
            type?: string;
            properties?: {
                [key: string]: unknown;
            };
            middlewares?: components["schemas"]["FileStoreMiddlewareUsage"][];
            files?: components["schemas"]["FileStoreEntry"][];
        };
        SystemConfiguration: {
            configKey?: string;
            configValue?: string;
        };
        NewRecordContent: {
            type?: string;
            properties?: {
                [key: string]: unknown;
            };
        };
        ListElement: {
            id?: string;
            parent?: components["schemas"]["ListType"];
            name?: string;
            description?: string;
            /** Format: int32 */
            elementIndex?: number;
            /** Format: date-time */
            activeTo?: string;
            aliases?: string[];
        };
        ListType: {
            id?: string;
            name?: string;
            children?: components["schemas"]["ListElement"][];
        };
        ObjectPropertyObject: {
            id?: string;
            name?: string;
            description?: string;
            type?: components["schemas"]["PropertyTypeObject"];
            listType?: components["schemas"]["ListType"];
            validator?: string;
            securityFilter?: string;
            defaultValue?: unknown;
        };
        PropertyTypeObject: {
            name?: string;
        };
        Record: {
            /** Format: uuid */
            id?: string;
            title?: string;
            type?: components["schemas"]["RecordType"];
            revisions?: components["schemas"]["RecordRevision"][];
            properties?: {
                [key: string]: components["schemas"]["RecordPropertyValueObject"];
            };
        };
        RecordPropertyValueObject: {
            /** Format: uuid */
            id?: string;
            record?: components["schemas"]["Record"];
            property?: components["schemas"]["ObjectPropertyObject"];
            value?: unknown;
            valueRaw?: unknown;
        };
        RecordRevision: {
            /** Format: uuid */
            id?: string;
            /** Format: double */
            version?: number;
            /** Format: date-time */
            createdDate?: string;
            record?: components["schemas"]["Record"];
            file?: components["schemas"]["FileStoreEntry"];
        };
        RecordType: {
            id?: string;
            name?: string;
            description?: string;
            securityFilter?: string;
            /** @enum {string} */
            securityFilterUsage?: "HIDE_RECORD" | "HIDE_METADATA_AND_FILES" | "HIDE_FILES" | "SHOW_ALL";
            contentTypes?: string[];
            properties?: components["schemas"]["RecordTypePropertyObject"][];
        };
        RecordTypePropertyObject: {
            property?: components["schemas"]["ObjectPropertyObject"];
            default?: unknown;
        };
        NewFileStore: {
            type?: string;
            properties?: {
                [key: string]: unknown;
            };
            middlewares?: string[];
        };
        NewFileStoreMiddleware: {
            type?: string;
            properties?: {
                [key: string]: unknown;
            };
        };
        EnvironmentResponse: {
            workgroup?: string;
            plugins?: string[];
            database?: string;
        };
        AuthenticationResponse: {
            token?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "object {0} of type {1} not found",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    newRevision: {
        parameters: {
            query?: {
                ext?: string;
            };
            header?: {
                "Content-Disposition"?: string;
            };
            path: {
                id: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "object {0} of type {1} not found",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    fileStore_retrieveOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["FileStoreObject"];
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "object {0} of type {1} not found",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    fileStore_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["FileStoreObject"];
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "object {0} of type {1} not found",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    fileStore_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "object {0} of type {1} not found",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    middleware_retrieveOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["FileStoreMiddlewareObject"];
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "object {0} of type {1} not found",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    middleware_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["FileStoreMiddlewareObject"];
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "object {0} of type {1} not found",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    database_retrieveOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: Record<string, never>;
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    set: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["SystemConfiguration"];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    registerTemplate: {
        parameters: {
            query?: {
                includeDependencies?: boolean;
            };
            header?: never;
            path: {
                type: string;
                template: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "object {0} of type {1} not found",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    newRecord: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewRecordContent"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["Record"];
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "object {0} of type {1} not found",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    fileStore_retrieveAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: string[];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    fileStore_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewFileStore"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["FileStoreObject"];
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "object {0} of type {1} not found",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    middleware_retrieveAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: string[];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    middleware_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewFileStoreMiddleware"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["FileStoreMiddlewareObject"];
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "object {0} of type {1} not found",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: string;
                    };
                };
            };
            /** @description Authentication Failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "errorCode": "Username or password is incorrect",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "object {0} of type {1} not found",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    getTemplatesForType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: string[];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    getTemplatesForType_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: string[];
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "object {0} of type {1} not found",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    getTemplatesForType_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: string;
                template: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: Record<string, never>;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "object {0} of type {1} not found",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    getRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["Record"];
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "object {0} of type {1} not found",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    getRevisions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: number[];
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "object {0} of type {1} not found",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    getRecordTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: string[];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    getRecordType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["RecordType"];
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "object {0} of type {1} not found",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    getLists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: string[];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    getList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                list: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ListType"];
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "object {0} of type {1} not found",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    getListElement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                list: string;
                element: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ListElement"];
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "object {0} of type {1} not found",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    searchListElement: {
        parameters: {
            query: {
                value: string;
            };
            header?: never;
            path: {
                list: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ListElement"][];
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "object {0} of type {1} not found",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    getEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["EnvironmentResponse"];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    database_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    server_retrieveAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    server_retrieveOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: Record<string, never>;
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    redirect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auth_provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "object {0} of type {1} not found",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
    callback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auth_provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["AuthenticationResponse"];
                    };
                };
            };
            /** @description Authentication Failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "errorCode": "Username or password is incorrect",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "object {0} of type {1} not found",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
            /** @description Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "error": "Internal Server Error",
                     *       "timestamp": "2026-06-29T23:05:00Z"
                     *     }
                     */
                    "application/json": {
                        success?: boolean;
                        /** Format: date-time */
                        timestamp?: string;
                        data?: components["schemas"]["ApiResponseWrapper"];
                    };
                };
            };
        };
    };
}
